FROM ubuntu:16.10

RUN apt-get install -y \
    build-essential \
    wget \
    python3 \
    python3-dev \
    python3-numpy \
    python3-pip

ADD $PWD/requirements.gpu /requirements.gpu
RUN pip3 install -r /requirements.gpu

CMD ["/bin/bash"]

